"""empty message

Revision ID: 0725c9e7be57
Revises: 
Create Date: 2022-09-12 13:43:42.719667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0725c9e7be57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('game', 'application', 'tool', 'demo', 'dlc', 'music', name='game_type'), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('has_trading_cards', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('app_id', name=op.f('pk__games'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
